### ISSUE TITLE
Prefix on save

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/sublime-autoprefixer#2]
I'm not sure how exactly it should work, but some might want it to apply on pre_save instead of having to manually call it.

Maybe off by default, but ability to toggle it on a per file basis from the command palette?

**Comment by ctf0** [comment]
a temp solution ,install `hooks` and add the `autoprefixer` to `on_pre_save_language` in the syntax settings.

**Comment by marsjaninzmarsa** [comment]
+1

**Comment by PixelT** [comment]
+1
