### ISSUE TITLE
Could work with LESS / Sass files ?

### ISSUE THREAD

**Issue by raphaelgoetter** [sindresorhus/sublime-autoprefixer#26]
Could Autoprefixr work with .less or .scss files ?

**Comment by tyrann0us** [comment]
Just for your information.
Autoprefixer indeed works with the LESS syntax. Every time you use it, it will append a " ' " (without spaces) to your LESS file causing the CSS parser to fail.
So all you have to do is to remove the character every time you autoprefixed your LESS file.
