### ISSUE TITLE
add support to other props.

### ISSUE THREAD

**Issue by ctf0** [sindresorhus/sublime-autoprefixer#49]
how to add support for other properties like `box-sizing: border-box;`.

**Comment by sindresorhus** [comment]
`box-sizing` is already supported.

Issues regarding the output should be opened here: https://github.com/postcss/autoprefixer-core

**Comment by ctf0** [comment]
well ,unfortunately when i run the cmnd nothing gets added :(

**Comment by sindresorhus** [comment]
That's because it's not needed anymore in newer browsers. It only adds them when needed. Use the `browser` setting to target the browsers you want and you'll get the required prefixed props.

This is clearly documented at the top of the readme. Please always do before opening an issue:

> This plugin uses the Autoprefixer library to prefix properties and values according to the Can I Use database. Which means it will only add the necessary prefixes and not bloat your stylesheet. It even lets you specify what browsers you want to target. In addition it will remove existing prefixes which are no longer needed.

**Comment by ctf0** [comment]
thanx for the headsup
