### ISSUE TITLE
Yet another $PATH issue

### ISSUE THREAD

**Issue by joaocunha** [sindresorhus/sublime-autoprefixer#50]
> Yosemite 10.10.2
> nvm 0.23.3
> node v0.10.36
> Sublime Text 3 (stable 3065)

I tried all tricks I know to get node in my path, namely:

- `.zshrc`
- `/etc/launchd.conf`
- `/etc/paths.d`
- `launchctl setenv PATH $PATH`

...but I still get the error:
![image](https://cloud.githubusercontent.com/assets/766837/6187237/7ba4761e-b39d-11e4-958b-f7fc1b076977.png)

Maybe we could add `"node-path"` to the JSON config file so we can pass an arbitrary value? This is [what CSSComb is doing](https://github.com/csscomb/sublime-csscomb/blob/master/CSScomb.sublime-settings#L4).

**Comment by sindresorhus** [comment]
Where is your node binary located `$ which node`? On OS X GUI apps doesn't get the $PATH so I have to manually define it: https://github.com/sindresorhus/sublime-autoprefixer/blob/90711099ffa63987b2f6f6e1245f5779ee5e7902/node_bridge.py#L13

**Comment by joaocunha** [comment]
@sindresorhus 

> joaocunha% $ which node
> /Users/joaocunha/.nvm/v0.10.36/bin/node

I think a symlink would solve my issue, but making it configurable would be a good addition. I can PR that if you agree.

**Comment by sindresorhus** [comment]
I don't see the point in making it configurable when you can just symlink it. Symlinking it will fix it for all tools instead of having to have an option for all these tools.

**Comment by joaocunha** [comment]
Agreed. I think a notice in the readme for nvm users would do some good, tho.

Thanks!
