### ISSUE TITLE
'utf-8' codec can't decode byte 0xce

### ISSUE THREAD

**Issue by 66beta** [sindresorhus/sublime-autoprefixer#51]
Error msg: **'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte**

**windows 64bit, sublime text 3, files are all utf-8**

with this config will cause the error: ```"browsers": ["last 2 versions", "Firefox > 20"],```

with this config works fine: ```"browsers": ["last 2 versions"],```

**Comment by LOQUILLO** [comment]
Tested and this option does not work in my ST3.
Windows 7 x64, ST3 Dev Channel Build 3069

**Comment by darkkain** [comment]
Same error. Win 8.1 x64, st3 dev, all files utf-8.
Problem with ">" and "<", only those characters trow error

**Comment by sindresorhus** [comment]
Can anyone share a file that I can test with?

**Comment by darkkain** [comment]
autoprefixer settings:
```json
{
  "browsers": ["last 6 version", "> 10%", "ie 8", "ie 7"]
}
```
Ex, this css:
```css
.text{
    box-shadow: #fff;
}
```
![czxczcz](https://cloud.githubusercontent.com/assets/4064924/6621708/3a894d1a-c8e9-11e4-94a9-0efcef90b400.PNG)

**Comment by sindresorhus** [comment]
@darkkain Tried with the latest Sublime dev build on Windows 8.1 and could not reproduce. Can you share the actual files? Might be something about the encoding. I did do some other improvements to Windows support. So if you could make sure you're on the latest version, and try again, that would be super.

**Comment by darkkain** [comment]
@sindresorhus Sorry. I'm a loser :disappointed:
This step fix the "problem": 
1. Removing autoprefixer
2. Install autoprefixer
3. ... 
4. All okey :thumbsup:

**Comment by GeorgiosTsolakis** [comment]
@darkkain I face the same problem ("UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 3: invalid continuation byte"). As I just started learning python, could you please tell me how you remove and install autoprefixer? Thank you!
