### ISSUE TITLE
Target to browser market share in specific country

### ISSUE THREAD

**Issue by marsjaninzmarsa** [sindresorhus/sublime-autoprefixer#52]
Sublime Autoprefixer has an ability to target e.g "all browsers with market share of more than 10%" based on stats from caniuse.com. I wanna have an ability to specify target country - in Poland we have less Safari and IE and more Opera Browser, for example.

**Comment by kevva** [comment]
Please, try harder and include at least a couple of lines describing what your problem is next time.

**Comment by marsjaninzmarsa** [comment]
Duh, ok, I was thinking that it's obvious... Is it ok now?

**Comment by kevva** [comment]
It's already supported https://github.com/ai/browserslist#queries.

**Comment by marsjaninzmarsa** [comment]
Awesome, thanks! :D

**Comment by kevva** [comment]
:D.
