### ISSUE TITLE
Node.js problem

### ISSUE THREAD

**Issue by marsjaninzmarsa** [sindresorhus/sublime-autoprefixer#53]
>Autoprefixer
>Couldn't find Node.js. Make sure it's in your $PATH by running `node -v` in your command-line.

Ok, but...
```
C:\Users\user>node -v
v0.10.21
```

Where is the problem?

**Comment by kevva** [comment]
What does `where node` give you?

**Comment by marsjaninzmarsa** [comment]
Umm...
```
C:\Users\user>where node
C:\Chocolatey\bin\node
C:\Chocolatey\bin\node.bat
```

I think this should be the problem - node in `$PATH` is not `node.exe`, but `.bat` shortcut to `node.exe`...

**Comment by kevva** [comment]
Create a symlink to your `node.exe` and make sure it exists in `PATH`.

**Comment by mkdesignn** [comment]
hi i have the same problem but typing where node will print C:\Program Files\nodejs\node.exe
i dont really what to do ?
