### ISSUE TITLE
Linux $PATH issue

### ISSUE THREAD

**Issue by stv8** [sindresorhus/sublime-autoprefixer#55]
Hello, I am having issues with autoprefixer not finding nodejs in my $PATH. Running `node -v` in both bash and zsh yields the correct version but it seems that sublime cannot find it. The output of `which node` is `/home/sv/.nvm/v0.10.32/bin/node`.

Any ideas how to fix?

Thanks

**Comment by kevva** [comment]
Please, search the issue tracker for similar issues before opening a new one. This should fix your problem https://github.com/sindresorhus/sublime-autoprefixer/issues/50.

**Comment by stv8** [comment]
My apologies, I actually saw that issue but I dismissed it before even trying because I saw it was for OS X. This ended up working for me Linux Mint 16. 

Thanks
