### ISSUE TITLE
confusing instructions 

### ISSUE THREAD

**Issue by yairEO** [sindresorhus/sublime-autoprefixer#56]
`Install Autoprefixer with Package Control and restart Sublime.`

I am using sublime v3 and I am not seeing any `Autoprefixer` when going to `package control: install package`. it finds nothing of that sort

**Comment by sindresorhus** [comment]
Sure it's not a case of https://github.com/sindresorhus/sublime-autoprefixer/issues/41 ? ;)

**Comment by yairEO** [comment]
omg, I am sorry for wasting your time...

**Comment by sindresorhus** [comment]
No worries, I've done the same mistake before ;)
