### ISSUE TITLE
Doesn't work on my EOS '-(

### ISSUE THREAD

**Issue by dagolinuxoid** [sindresorhus/sublime-autoprefixer#57]
Hi there! Today I installed "Autoprefix CSS" on Sublime Tex 3 ( Build 3083), but unfortunately it doesn't works(. I just opened empty css file (some.css) and typing property that require vendor prefix 
```
a {
	transition: transform 1s;
}
```
after I run (through ctrl+shift+p) Autoprefix CSS but nothing happened, no change at all. PS. Linux Elementary OS Luna x 64
linux@linux-desktop:~$ node -v
v0.6.12
linux@linux-desktop:~$ 
Whats wrong with Autoprefix CSS or maybe with me?)), sorry I know my English is SO terrible, but hope you got it.

**Comment by sindresorhus** [comment]
Maybe it doesn't have to be prefixed. That depends on the browsers you choose to support in the settings.

**Comment by dagolinuxoid** [comment]
Well... default settings (actually flex value for display property also doesn't works for instance)

**Comment by sindresorhus** [comment]
Oh, just noticed you're on a ancient node version. Upgrade to latest node and it should work.

**Comment by dagolinuxoid** [comment]
Thx a lot! 
```
sudo add-apt-repository ppa:chris-lea/node.js  
sudo apt-get update  
sudo apt-get install nodejs
linux@linux-desktop:~$ node -v
v0.10.37
``` 
Works like a charm now.
