### ISSUE TITLE
Couldn't find Node.js

### ISSUE THREAD

**Issue by sublines** [sindresorhus/sublime-autoprefixer#58]
I am running Sublime Text 3 Build 3083 on Win8.1 an have just installed Autoprefixer using Package Control. NodeJS was installed manually afterwards. 
However, when I try to run AP I get the following Error:

> Autoprefixer
> Couldn't find Node.js. Make sure it's in your $PATH by running 'node -v' in your command-line.

So I did that and it shows
> v0.12.7

Running 'where node' in cmd shows
> C:\Program Files\nodejs\node.exe

And that is the correct path of node.exe 
This path is also set in my system variables
Looking through #45 did not help

**Comment by sindresorhus** [comment]
Are you using a Node.js version manager by any chance?

**Comment by Akurganow** [comment]
Have the same problem, and yes, i'm using nvm

**Comment by soenkekluth** [comment]
+1 please just make the node path configurable.

**Comment by sindresorhus** [comment]
Please learn how `nvm` works. You can set `nvm alias default stable`. Or use a better node version managerl like [n](https://github.com/tj/n). Configurability is in most cases the problem not the solution.

**Comment by soenkekluth** [comment]
so please just tell me shortly why you do not check for node and or autoprefixer as a service instead of checking a specific installation path?

**Comment by Akurganow** [comment]
@sindresorhus And how `nvm alias default stable` can help with this?
I do it and plugin still not work.

>use a better node version manager

Please do not tell me what software I should use

**Comment by sindresorhus** [comment]
@soenkekluth No idea what you mean by service, but on OS X we don't get the user's PATH, so we're stuck with hard-coding the path. You can symlink your Node.js binary, wherever it is, into `/usr/local/bin` and it will work. This is better than an option as it will work with any script requiring Node.js.

**Comment by sindresorhus** [comment]
@Akurganow 

> Please do not tell me what software I should use

I did not. It was a recommendation as `nvm` doesn't expose the currently chosen Node.js to scripts by default, `n` does. But I am going to tell what software not to use, mine.
