### ISSUE TITLE
Support SCSS

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/sublime-autoprefixer#59]
Now supported through a custom parser in [autoprefixer@6.0.0](https://github.com/postcss/autoprefixer/releases/tag/6.0.0):
https://github.com/postcss/postcss/#custom-syntaxes
https://github.com/postcss/postcss-scss

I don't have time to do this right now, but PR welcome :)

**Comment by gjjones** [comment]
Do you mind if this project takes on [postcss-scss](https://github.com/postcss/postcss-scss) as a dep for the feature?

I guess it depends on whether you want this extra syntax to bring about a plugin style system or if it is alright to own capabilities for what `sublime-autoprefixer` can do.

**Comment by sindresorhus** [comment]
Sure. You can see how it was solved in https://github.com/sindresorhus/atom-autoprefixer/commit/fc02483a98e2cd5124fa103955a2577817f8ba84.
