### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by alexdevero** [sindresorhus/sublime-autoprefixer#61]
Since today, I got an error about "ReferenceError: Promise is not defined" on lazy-result.js:150 this.processing = new Promise(function (resolve, reject).
![cojj8h9veaa0a2_](https://cloud.githubusercontent.com/assets/4237724/9699476/11d64706-53e5-11e5-8985-02f622d3fa4e.png)

**Comment by sindresorhus** [comment]
Upgrade Node.js

**Comment by martellalex** [comment]
I did $nvm install 0.12.7 in both the directory I'm working in and also the autoprefixer directory, and also the sublime text 3 directory, I still get the same error as @alexdevero 

Any ideas?

**Comment by sindresorhus** [comment]
I'm tired of giving NVM support, but here goes; NVM doesn't expose the Node.js version for external tools. Use a better Node.js manager or set the default Node.js version as explained in the NVM readme. If nothing else works, download the package installer from https://nodejs.org/en/
