### ISSUE TITLE
Error upon save

### ISSUE THREAD

**Issue by eduard-ungureanu** [sindresorhus/sublime-autoprefixer#66]
Hi and thank you for this amanzing plugin, unfortuneatly on mac OS X El Capitan, and Sublime Text 3, If in the User Settings I set:
```
{
    "prefixOnSave": true
}
```
Once I save the css file I got this:
![screen shot 2016-01-11 at 7 14 55 pm](https://cloud.githubusercontent.com/assets/1719735/12240704/9da10098-b897-11e5-9979-9b1e775eecd4.png)

Is there something from my end?

Thank you in advance
Best Regards.

**Comment by sindresorhus** [comment]
From the readme:

> **You need to have Node.js >=0.12.0 installed.**
