### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ollakalla** [sindresorhus/sublime-autoprefixer#69]
I have install Autoprefixer from Package Controller as the documentation on windows machine
and make sure that i have node installed with version v5.3.0
but it is not working. when i use the shortcut ctrl+alt+x

**Comment by kevva** [comment]
Does it work when using it from the command palette (Cmd+Shift+P)?

**Comment by sindresorhus** [comment]
Probably a duplicate of https://github.com/sindresorhus/sublime-autoprefixer/issues/68#issuecomment-192837311.

**Comment by kevva** [comment]
I thought he wasn't able to use it, not that he couldn't find it?

**Comment by sindresorhus** [comment]
Oh, I linked to the wrong issue, but the deal is that he probably tried to autoprefix something that didn't need prefixing and nothing happened.

**Comment by kevva** [comment]
Probably, yeah.

**Comment by ollakalla** [comment]
i try box-shadow but didn't work

**Comment by kevva** [comment]
`box-shadow` doesn't need prefixing.

**Comment by ollakalla** [comment]
Could you give me something to test :D

**Comment by kevva** [comment]
Try `flex: 0 0 100%`.
