### ISSUE TITLE
Problem with autoprefixer not putting in Safari vendor codes

### ISSUE THREAD

**Issue by Asimov500** [sindresorhus/sublime-autoprefixer#70]
I have used autoprefixer for a while and recently I upgraded to windows 10, so I am not sure if that is connected to the issue or not.
The problem is that when I run autoprefixer it is not putting in Safari vendor codes.

I tested it with the following code
.flexjustify_space {
        justify-content: space-between;
}
.equalHW {
        flex: 1;
}
.equalHWdetails {
        flex: 0 0 25%;
}

And I got this output
.flexjustify_space {
        -ms-flex-pack: justify;
            justify-content: -between;
}space
.equalHW {
        -ms-flex: 1;
            flex: 1;
}
.equalHWdetails {
        -ms-flex: 0 0 25%;
            flex: 0 0 25%;
}

It has added vendor code but no Safari Vendor code. I had to manually insert it, which defeats the purpose of autoprefixer.
eg
display: -webkit-flex; /* Safari */
-webkit-justify-content: space-between;

Am I the only one to have this problem?

**Comment by sindresorhus** [comment]
What's being added depends on what browsers you've configured to support: https://github.com/sindresorhus/sublime-autoprefixer#example
