### ISSUE TITLE
Autoprefixer not working in Sublime Text 3

### ISSUE THREAD

**Issue by anthonypecchillo** [sindresorhus/sublime-autoprefixer#72]
I have installed Autoprefixer via Package Control, made sure my syntax is set to CSS (not CSS3, as I've seen others having trouble with that), made sure to restart Sublime, but still Autoprefixer does nothing to my code.

For example, when the following is highlighted and Autoprefixer is run:

.container {
	transition: all 1s;
}

Nothing happens.  Help?

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/sublime-autoprefixer/issues/70.
