### ISSUE TITLE
autoprefixer stopped to work on sublime text 3 today

### ISSUE THREAD

**Issue by locougil** [sindresorhus/sublime-autoprefixer#75]
Today, I tried to run autoprefixer to one of my css file as usual. And i got this popup message. See the preenscreen below.  I'dont understand why ? I have installed sublime text 3 and all the packages with the package control of sublime text 3. A few days before everything worked fine..  it's a misunderstanding for me. I tried to reinstall autoprefixer package ... but it dosen't change anything.. someone can help me to find the problem ? Thanks a lot
![Capture](https://user-images.githubusercontent.com/46594787/67394473-86694b80-f5a4-11e9-8345-ded01e2478aa.PNG)
![Capture_2](https://user-images.githubusercontent.com/46594787/67394491-91bc7700-f5a4-11e9-9012-877da3eb850f.PNG)

**Comment by Draghmar** [comment]
I can confirm that I got the same thing today. I think yesterday or day before that it was working as usual. I did try to update through npm but that broke it even further. ;)
