### ISSUE TITLE
Autoprefixer Couldn't find Node.js 

### ISSUE THREAD

**Issue by candreslobor** [sindresorhus/sublime-autoprefixer#77]
So the problem is this, i've installed nodejs in my linux system with nvm, in fact if i type `node -v` in terminal i get my current version of node, to be clear, the problem is that autoprefixer cannot find nodejs.

BTW: i'm currently using a linux ubuntu/debian distro (Zorin OS)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/sublime-autoprefixer/issues/76#issuecomment-596203145

**Comment by candreslobor** [comment]
> [#76 (comment)](https://github.com/sindresorhus/sublime-autoprefixer/issues/76#issuecomment-596203145)

i tried making a symblink but it doesn't work
