### ISSUE TITLE
Error: Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by ashucg** [sindresorhus/sublime-autoprefixer#78]
I had to update npm packages to fix this problem. Running `npm update` didn't work straight away, had to delete **node_modules** directory first.

**Comment by Rufi512** [comment]
I found another possible solution
After updating with "npm update"

Copy the caniuse-lite and browser-sync folders located at Appdata / Roaming / npm / node_modules and then paste them AppData / Roaming / Sublime Text 3 / Packages / Autoprefixer / node_modules

at least for me I solve that error

**Comment by lear2000** [comment]
copying only  / npm / node_modules /**caniuse-lite** >  / Sublime Text 3 / Packages / Autoprefixer / node_modules

worked for me

**Comment by ashucg** [comment]
> I found another possible solution
> After updating with "npm update"
> 
> Copy the caniuse-lite and browser-sync folders located at Appdata / Roaming / npm / node_modules and then paste them AppData / Roaming / Sublime Text 3 / Packages / Autoprefixer / node_modules
> 
> at least for me I solve that error

`npm update` didn't work for me on Linux (Fedora 31) that's why I had to delete the directory.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/sublime-autoprefixer/commit/7907e3dac991a865c3873446c2dcde244eb210f0.

**Comment by Juribiyan** [comment]
The error still occurs

**Comment by dylan-hatch** [comment]
Can confirm this error still occurs
