### ISSUE TITLE
Error while installing Autoprefixer

### ISSUE THREAD

**Issue by shrihanDev** [sindresorhus/sublime-autoprefixer#80]
# Hello!
Today, I was trying to install Autoprefixer in Sublime Text.
When I finished installing, it showed me this:

![](https://user-images.githubusercontent.com/54971391/80860201-d1ff5f00-8c83-11ea-9da8-07af086daf01.PNG)

I tried to reinstall so many times, still no luck.
Please suggest me.

**Comment by sindresorhus** [comment]
That looks like a problem with Package Control. This package probably got corrupted somehow while installing. Try asking on the Package Control support forums.
