### ISSUE TITLE
Error: spawn npx ENOENT

### ISSUE THREAD

**Issue by igor-ws** [sindresorhus/sublime-autoprefixer#82]
Hello, I get this error with autoprefixer:

> error: Autoprefixer
> Error: events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> Error: spawn npx ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn npx',
>   path: 'npx',
>   spawnargs: [ 'browserslist@latest', '--update-db' ]
> }

Last week I updated browsers list with _npx browserslist@latest --update-db_, everything worked fine.
Win10. Node version 12.18.1.

Any help much appreciated.

**Comment by ly20000814bx** [comment]
hello, Run the NPX browserslist@latest --update-db command ？ Wouldn't you have reported the error？
