### ISSUE TITLE
Problems with ::placeholder

### ISSUE THREAD

**Issue by ivancasasempere** [sindresorhus/sublime-autoprefixer#85]
If i have this code:

`
.form-group input[type="text"]::-moz-placeholder,
.form-group input[type="password"]::-moz-placeholder {
    color: #C1C2C4;
}

.form-group input[type="text"]:-ms-input-placeholder,
.form-group input[type="password"]:-ms-input-placeholder {
    color: #C1C2C4;
}

.form-group input[type="text"]::placeholder,
.form-group input[type="password"]::placeholder {
    color: #C1C2C4;
}
`

When i save its adding me another time the same :-ms-input-placeholder and ::-moz-placeholder

`.form-group input[type="text"]::-moz-placeholder,
.form-group input[type="password"]::-moz-placeholder {
    color: #C1C2C4;
}

.form-group input[type="text"]:-ms-input-placeholder,
.form-group input[type="password"]:-ms-input-placeholder {
    color: #C1C2C4;
}

.form-group input[type="text"]::-moz-placeholder, .form-group input[type="password"]::-moz-placeholder {
    color: #C1C2C4;
}

.form-group input[type="text"]:-ms-input-placeholder, .form-group input[type="password"]:-ms-input-placeholder {
    color: #C1C2C4;
}

.form-group input[type="text"]::placeholder,
.form-group input[type="password"]::placeholder {
    color: #C1C2C4;
}`

It only happens when is in two fields. Not inline.

**Comment by sindresorhus** [comment]
Closing for staleness and also because this should have been reported on the main Autoprefixer repo.
