### ISSUE TITLE
Unkown error

### ISSUE THREAD

**Issue by jimishsoni1990** [sindresorhus/sublime-autoprefixer#86]
When i try to apply autoprefixer, it shows following error: 

![sublime-error](https://user-images.githubusercontent.com/17750115/120596750-bd326380-c461-11eb-8f6e-eeda55a9029d.png)

Let me know if you need any other info for debugging. Thank you.

**Comment by sindresorhus** [comment]
Cannot reproduce with latest version. Make sure you are on Node.js 20.
