### ISSUE TITLE
Autoprefixer Error: (node:9236) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module 

### ISSUE THREAD

**Issue by kampiamodikuesto** [sindresorhus/sublime-autoprefixer#87]
hi, i get this error when try to use this sublime extension. I'm on bigsure with node last version 16.

Anyone with same error?

**Comment by jsongerber** [comment]
Hi, just had this error too.
For a quick fix I just did a `npm update` into the package folder:

(The path on a MacOS it's someting like `/Users/{username}/Library/Application\ Support/Sublime\ Text/Packages/Autoprefixer`)

`$ cd {path_to_package}/Autoprefixer`
`$ npm update`

Not sure if it will works over time but it does now

**Comment by Draghmar** [comment]
Yup, it does for me as well. Thanks for the tip!

**Comment by sindresorhus** [comment]
Cannot reproduce with latest version. Make sure you are on Node.js 20.
