### ISSUE TITLE
Autoprefixer on save, error loader:544

### ISSUE THREAD

**Issue by foggy748** [sindresorhus/sublime-autoprefixer#88]
Hello, I have some issues with the plugin. When I save, this pop appear.

![image](https://user-images.githubusercontent.com/56768129/224562018-05678605-79fa-4a18-a00f-8ca09e356607.png)

Can you help me, please ?

**Comment by zovatrop** [comment]
Which version of node.js are you using? Tray uninstalling node.js and installing version 15 https://nodejs.org/en/download/releases. That worked for me.

**Comment by risejs** [comment]
Update node modules in the plugin folder.

Windows Command Prompt:
`cd %AppData%\Sublime Text\Packages\Autoprefixer`
`npm update`

[MacOS](https://github.com/sindresorhus/sublime-autoprefixer/issues/87#issuecomment-908212356)

**Comment by sindresorhus** [comment]
Cannot reproduce with latest version. Make sure you are on Node.js 20.
